#include <stdio.h>
#include <stdbool.h>
/**
  * main - Entry point.
  * Return: 0 if successful.
  *
  * Each new term in the Fibonacci sequence is generated by adding the
  * previous two terms. By starting with 1 and 2, the first 10 terms will be:
  * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  * By considering the terms in the Fibonacci sequence whose values do not
  * exceed four million, find the sum of the even-valued terms.
  */
int main(void)
{
	int times = true;
	int limit = 4000000;
	int a = 0;
	int b = 1;
	int fibonacci = 0;
	unsigned long long sum = 0;

	while (times)
	{
		fibonacci = a + b;
		a = b;
		b = fibonacci;
		if (fibonacci % 2 == 0)
			sum += fibonacci;
		if (fibonacci >= limit)
			times = false;
	}
	printf("%llu\n", sum);
	return (0);
}
